"""Execution-in-progress preemption contract, independent of PPO/GPPO."""

from .controller import PreemptionController
from .allocation import (
    AllocationCandidate,
    AllocationProposal,
    AllocationRequest,
    AllocationValidationError,
    CallbackAllocator,
    FirstAvailableAllocator,
    MaxEnergyMarginAllocator,
    build_allocation_request,
    validate_proposal,
)
from .models import (
    CommandStatus,
    CommunicationState,
    DecisionType,
    EventDecision,
    EventPriority,
    ExecutionCommand,
    ProgressPolicy,
    ResumePolicy,
    RuntimeEvent,
    RuntimeEventType,
    TaskProgressRecord,
    TaskRuntime,
    TaskState,
    UAVAvailability,
    UAVRuntime,
)
from .runtime import (
    EventBatchResult,
    ExecutionRuntime,
    RuntimeInvariantError,
    StaleExecutionCommand,
)

__all__ = [
    "CommandStatus",
    "AllocationCandidate",
    "AllocationProposal",
    "AllocationRequest",
    "AllocationValidationError",
    "CallbackAllocator",
    "CommunicationState",
    "DecisionType",
    "EventBatchResult",
    "EventDecision",
    "EventPriority",
    "ExecutionCommand",
    "ExecutionRuntime",
    "FirstAvailableAllocator",
    "MaxEnergyMarginAllocator",
    "PreemptionController",
    "ProgressPolicy",
    "ResumePolicy",
    "RuntimeEvent",
    "RuntimeEventType",
    "RuntimeInvariantError",
    "StaleExecutionCommand",
    "TaskProgressRecord",
    "TaskRuntime",
    "TaskState",
    "UAVAvailability",
    "UAVRuntime",
    "build_allocation_request",
    "validate_proposal",
]
